
# Lista de vehículos con sus características
# Este código almacena la información de una flota de vehículos y sus respectivos propietarios.
# La lista `vehiculos` contiene diccionarios donde cada uno representa un vehículo con su placa, 
# tipo (carro o moto), marca, modelo, y si tiene el marchamo vigente o no.

vehiculos = [
    {"Placa":"ABC001", "tipo": "carro", "marca": "Toyota", "modelo": "Corolla", "Marchamo": "Sí"},
    {"Placa":"ABC002", "tipo": "moto", "marca": "Yamaha", "modelo": "MT-07", "Marchamo": "No"},
    {"Placa":"ABC003", "tipo": "carro", "marca": "Ford", "modelo": "F-150", "Marchamo": "Sí"},
    {"Placa": "ABC004", "tipo": "carro", "marca": "Chevrolet", "modelo": "Silverado", "Marchamo": "No"},
    {"Placa": "ABC005", "tipo": "moto", "marca": "Honda", "modelo": "CBR500R", "Marchamo": "Sí"},
    {"Placa": "ABC006", "tipo": "carro", "marca": "Nissan", "modelo": "Altima", "Marchamo": "No"},
    {"Placa": "ABC007", "tipo": "carro", "marca": "Honda", "modelo": "Civic", "Marchamo": "Sí"},
    {"Placa": "ABC008", "tipo": "moto", "marca": "Suzuki", "modelo": "GSX-R750", "Marchamo": "No"},
    {"Placa": "ABC009", "tipo": "carro", "marca": "Toyota", "modelo": "Camry", "Marchamo": "Sí"},
    {"Placa": "ABC010", "tipo": "moto", "marca": "Kawasaki", "modelo": "Ninja 650", "Marchamo": "No"},
    {"Placa": "ABC011", "tipo": "carro", "marca": "Ford", "modelo": "Explorer", "Marchamo": "Sí"},
    {"Placa": "ABC012", "tipo": "carro", "marca": "Chevrolet", "modelo": "Tahoe", "Marchamo": "No"},
    {"Placa": "ABC013", "tipo": "moto", "marca": "Ducati", "modelo": "Monster 821", "Marchamo": "Sí"},
    {"Placa": "ABC014", "tipo": "carro", "marca": "Nissan", "modelo": "Sentra", "Marchamo": "No"},
    {"Placa": "ABC015", "tipo": "carro", "marca": "Honda", "modelo": "Accord", "Marchamo": "Sí"},
    {"Placa": "ABC016", "tipo": "moto", "marca": "Yamaha", "modelo": "R1", "Marchamo": "No"},
    {"Placa": "ABC017", "tipo": "carro", "marca": "Toyota", "modelo": "RAV4", "Marchamo": "Sí"},
    {"Placa": "ABC018", "tipo": "carro", "marca": "Ford", "modelo": "Escape", "Marchamo": "No"},
    {"Placa": "ABC019", "tipo": "moto", "marca": "Honda", "modelo": "CRF450R", "Marchamo": "Sí"},
    {"Placa": "ABC020", "tipo": "carro", "marca": "Chevrolet", "modelo": "Malibu", "Marchamo": "No"},
    {"Placa": "ABC021", "tipo": "moto", "marca": "Suzuki", "modelo": "SV650", "Marchamo": "Sí"},
    {"Placa": "ABC022", "tipo": "carro", "marca": "Nissan", "modelo": "Maxima", "Marchamo": "No"},
    {"Placa": "ABC023", "tipo": "carro", "marca": "Honda", "modelo": "Pilot", "Marchamo": "Sí"},
    {"Placa": "ABC024", "tipo": "moto", "marca": "Kawasaki", "modelo": "Z900", "Marchamo": "No"},
    {"Placa": "ABC025", "tipo": "carro", "marca": "Toyota", "modelo": "Highlander", "Marchamo": "Sí"},
    {"Placa": "ABC026", "tipo": "carro", "marca": "Ford", "modelo": "Mustang", "Marchamo": "No"},
    {"Placa": "ABC027", "tipo": "moto", "marca": "Ducati", "modelo": "Panigale V2", "Marchamo": "Sí"},
    {"Placa": "ABC028", "tipo": "carro", "marca": "Chevrolet", "modelo": "Traverse", "Marchamo": "No"},
    {"Placa": "ABC029", "tipo": "moto", "marca": "Yamaha", "modelo": "Tracer 900", "Marchamo": "Sí"},
    {"Placa": "ABC030", "tipo": "carro", "marca": "Nissan", "modelo": "Rogue", "Marchamo": "No"},
    {"Placa": "ABC031", "tipo": "carro", "marca": "Honda", "modelo": "Ridgeline", "Marchamo": "Sí"},
    {"Placa": "ABC032", "tipo": "moto", "marca": "Suzuki", "modelo": "DR-Z400", "Marchamo": "No"},
    {"Placa": "ABC033", "tipo": "carro", "marca": "Toyota", "modelo": "4Runner", "Marchamo": "Sí"},
    {"Placa": "ABC034", "tipo": "carro", "marca": "Ford", "modelo": "Fusion", "Marchamo": "No"},
    {"Placa": "ABC035", "tipo": "moto", "marca": "Honda", "modelo": "CB300R", "Marchamo": "Sí"},
    {"Placa": "ABC036", "tipo": "carro", "marca": "Chevrolet", "modelo": "Blazer", "Marchamo": "No"},
    {"Placa": "ABC037", "tipo": "moto", "marca": "Kawasaki", "modelo": "Versys 650", "Marchamo": "Sí"},
    {"Placa": "ABC038", "tipo": "carro", "marca": "Nissan", "modelo": "Murano", "Marchamo": "No"},
    {"Placa": "ABC039", "tipo": "carro", "marca": "Honda", "modelo": "Odyssey", "Marchamo": "Sí"},
    {"Placa": "ABC040", "tipo": "moto", "marca": "Yamaha", "modelo": "XSR900", "Marchamo": "No"},
    {"Placa": "ABC041", "tipo": "carro", "marca": "Toyota", "modelo": "Tacoma", "Marchamo": "Sí"},
    {"Placa": "ABC042", "tipo": "carro", "marca": "Ford", "modelo": "Edge", "Marchamo": "No"},
    {"Placa": "ABC043", "tipo": "moto", "marca": "Ducati", "modelo": "Scrambler", "Marchamo": "Sí"},
    {"Placa": "ABC044", "tipo": "carro", "marca": "Chevrolet", "modelo": "Equinox", "Marchamo": "No"},
    {"Placa": "ABC045", "tipo": "moto", "marca": "Yamaha", "modelo": "MT-09", "Marchamo": "Sí"},
    {"Placa": "ABC046", "tipo": "carro", "marca": "Nissan", "modelo": "Pathfinder", "Marchamo": "No"},
    {"Placa": "ABC047", "tipo": "carro", "marca": "Honda", "modelo": "CR-V", "Marchamo": "Sí"},
    {"Placa": "ABC048", "tipo": "moto", "marca": "Suzuki", "modelo": "GSX-S750", "Marchamo": "No"},
    {"Placa": "ABC049", "tipo": "carro", "marca": "Toyota", "modelo": "Sequoia", "Marchamo": "Sí"},
    {"Placa": "ABC050", "tipo": "carro", "marca": "Ford", "modelo": "Bronco", "Marchamo": "No"},
    {"Placa": "ABC051", "tipo": "moto", "marca": "Honda", "modelo": "CBR650R", "Marchamo": "Sí"},
    {"Placa": "ABC052", "tipo": "carro", "marca": "Chevrolet", "modelo": "Suburban", "Marchamo": "No"},
    {"Placa": "ABC053", "tipo": "moto", "marca": "Kawasaki", "modelo": "Z650", "Marchamo": "Sí"},
    {"Placa": "ABC054", "tipo": "carro", "marca": "Nissan", "modelo": "Armada", "Marchamo": "No"},
    {"Placa": "ABC055", "tipo": "carro", "marca": "Honda", "modelo": "HR-V", "Marchamo": "Sí"},
    {"Placa": "ABC056", "tipo": "moto", "marca": "Yamaha", "modelo": "MT-07", "Marchamo": "No"},
    {"Placa": "ABC057", "tipo": "carro", "marca": "Toyota", "modelo": "Sienna", "Marchamo": "Sí"},
    {"Placa": "ABC058", "tipo": "carro", "marca": "Ford", "modelo": "Ranger", "Marchamo": "No"},
    {"Placa": "ABC059", "tipo": "moto", "marca": "Ducati", "modelo": "Multistrada", "Marchamo": "Sí"},
    {"Placa": "ABC060", "tipo": "carro", "marca": "Chevrolet", "modelo": "Colorado", "Marchamo": "No"},
    {"Placa": "ABC061", "tipo": "moto", "marca": "Suzuki", "modelo": "GSX250R", "Marchamo": "Sí"},
    {"Placa": "ABC062", "tipo": "carro", "marca": "Nissan", "modelo": "Versa", "Marchamo": "No"},
    {"Placa": "ABC063", "tipo": "carro", "marca": "Honda", "modelo": "Fit", "Marchamo": "Sí"},
    {"Placa": "ABC064", "tipo": "moto", "marca": "Kawasaki", "modelo": "Ninja 400", "Marchamo": "No"},
    {"Placa": "ABC065", "tipo": "carro", "marca": "Toyota", "modelo": "Yaris", "Marchamo": "Sí"},
    {"Placa": "ABC066", "tipo": "carro", "marca": "Ford", "modelo": "F-150", "Marchamo": "No"},
    {"Placa": "ABC067", "tipo": "moto", "marca": "Ducati", "modelo": "Diavel", "Marchamo": "Sí"},
    {"Placa": "ABC068", "tipo": "carro", "marca": "Chevrolet", "modelo": "Spark", "Marchamo": "No"},
    {"Placa": "ABC069", "tipo": "moto", "marca": "Yamaha", "modelo": "YZF-R6", "Marchamo": "Sí"},
    {"Placa": "ABC070", "tipo": "carro", "marca": "Nissan", "modelo": "Note", "Marchamo": "No"},
    {"Placa": "ABC071", "tipo": "carro", "marca": "Honda", "modelo": "Insight", "Marchamo": "Sí"},
    {"Placa": "ABC072", "tipo": "moto", "marca": "Suzuki", "modelo": "SV650X", "Marchamo": "No"},
    {"Placa": "ABC073", "tipo": "carro", "marca": "Toyota", "modelo": "Corolla", "Marchamo": "Sí"},
    {"Placa": "ABC074", "tipo": "carro", "marca": "Ford", "modelo": "Expedition", "Marchamo": "No"},
    {"Placa": "ABC075", "tipo": "moto", "marca": "Honda", "modelo": "Africa Twin", "Marchamo": "Sí"},
    {"Placa": "ABC076", "tipo": "carro", "marca": "Chevrolet", "modelo": "Camaro", "Marchamo": "No"},
    {"Placa": "ABC077", "tipo": "moto", "marca": "Kawasaki", "modelo": "Ninja ZX-6R", "Marchamo": "Sí"},
    {"Placa": "ABC078", "tipo": "carro", "marca": "Nissan", "modelo": "370Z", "Marchamo": "No"},
    {"Placa": "ABC079", "tipo": "carro", "marca": "Honda", "modelo": "Element", "Marchamo": "Sí"},
    {"Placa": "ABC080", "tipo": "moto", "marca": "Suzuki", "modelo": "Hayabusa", "Marchamo": "No"},
    {"Placa": "ABC081", "tipo": "carro", "marca": "Toyota", "modelo": "Prius", "Marchamo": "Sí"},
    {"Placa": "ABC082", "tipo": "carro", "marca": "Ford", "modelo": "Flex", "Marchamo": "No"},
    {"Placa": "ABC083", "tipo": "moto", "marca": "Ducati", "modelo": "Hypermotard", "Marchamo": "Sí"},
    {"Placa": "ABC084", "tipo": "carro", "marca": "Chevrolet", "modelo": "Sonic", "Marchamo": "No"},
    {"Placa": "ABC085", "tipo": "moto", "marca": "Yamaha", "modelo": "YZF-R1", "Marchamo": "Sí"},
    {"Placa": "ABC086", "tipo": "carro", "marca": "Nissan", "modelo": "Versa Note", "Marchamo": "No"},
    {"Placa": "ABC087", "tipo": "carro", "marca": "Honda", "modelo": "City", "Marchamo": "Sí"},
    {"Placa": "ABC088", "tipo": "moto", "marca": "Suzuki", "modelo": "GSX250R", "Marchamo": "No"},
    {"Placa": "ABC089", "tipo": "carro", "marca": "Toyota", "modelo": "Prius Prime", "Marchamo": "Sí"},
    {"Placa": "ABC090", "tipo": "carro", "marca": "Ford", "modelo": "Edge ST", "Marchamo": "No"},
    {"Placa": "ABC091", "tipo": "moto", "marca": "Honda", "modelo": "Grom", "Marchamo": "Sí"},
    {"Placa": "ABC092", "tipo": "carro", "marca": "Nissan", "modelo": "370Z", "Marchamo": "No"},
    {"Placa": "ABC093", "tipo": "carro", "marca": "Honda", "modelo": "CR-Z", "Marchamo": "Sí"},
    {"Placa": "ABC094", "tipo": "moto", "marca": "Kawasaki", "modelo": "Ninja H2", "Marchamo": "No"},
    {"Placa": "ABC095", "tipo": "carro", "marca": "Toyota", "modelo": "Land Cruiser", "Marchamo": "Sí"},
    {"Placa": "ABC096", "tipo": "carro", "marca": "Ford", "modelo": "Escape Hybrid", "Marchamo": "No"},
    {"Placa": "ABC097", "tipo": "moto", "marca": "Ducati", "modelo": "959 Panigale", "Marchamo": "Sí"},
    {"Placa": "ABC098", "tipo": "carro", "marca": "Chevrolet", "modelo": "Trax", "Marchamo": "No"},
    {"Placa": "ABC099", "tipo": "moto", "marca": "Yamaha", "modelo": "YZF-R3", "Marchamo": "Sí"},
    {"Placa": "ABC100", "tipo": "carro", "marca": "Nissan", "modelo": "Altima", "Marchamo": "No"}
]


# Lista de usuarios con sus datos personales y la placa del vehículo que poseen
# La lista `nombre_usuarios` contiene diccionarios donde cada uno representa a un usuario, 
# identificando su número de cédula, nombre completo, y la placa del vehículo que posee.
#
# Este tipo de estructura es útil para sistemas de administración de vehículos, 
# donde es necesario relacionar a los usuarios con los vehículos que poseen.

nombre_usuarios = [ 
    {"Cédula": 123352789, "Nombre": "Juan Perez Garcia", "Placa": "ABC001"},
    {"Cédula": 234567890, "Nombre": "Maria Lopez Martinez", "Placa": "ABC002"},
    {"Cédula": 346578901, "Nombre": "Carlos Rodriguez Sanchez", "Placa": "ABC003"},
    {"Cédula": 456881022, "Nombre": "Ana Gonzalez Hernandez", "Placa": "ABC004"},
    {"Cédula": 567880233, "Nombre": "Pedro Martinez Lopez", "Placa": "ABC005"},
    {"Cédula": 678901322, "Nombre": "Laura Perez Rodriguez", "Placa": "ABC006"},
    {"Cédula": 780912333, "Nombre": "Jorge Sanchez Gonzalez", "Placa": "ABC007"},
    {"Cédula": 890123486, "Nombre": "Sofia Hernandez Perez", "Placa": "ABC008"},
    {"Cédula": 203334576, "Nombre": "Diego Garcia Martinez", "Placa": "ABC009"},
    {"Cédula": 313395872, "Nombre": "Carmen Martinez Gonzalez", "Placa": "ABC010"},
    {"Cédula": 124356789, "Nombre": "Manuel Sanchez Lopez", "Placa": "ABC011"},
    {"Cédula": 436457890, "Nombre": "Luis Rodriguez Perez", "Placa": "ABC012"},
    {"Cédula": 645678901, "Nombre": "Elena Perez Martinez", "Placa": "ABC013"},
    {"Cédula": 556789012, "Nombre": "Isabel Gonzalez Sanchez", "Placa": "ABC014"},
    {"Cédula": 267890123, "Nombre": "Antonio Martinez Hernandez", "Placa": "ABC015"},
    {"Cédula": 178901234, "Nombre": "Paula Rodriguez Lopez", "Placa": "ABC016"},
    {"Cédula": 189812245, "Nombre": "Mario Sanchez Rodriguez", "Placa": "ABC017"},
    {"Cédula": 390123456, "Nombre": "Julia Hernandez Gonzalez", "Placa": "ABC018"},
    {"Cédula": 501234567, "Nombre": "Roberto Garcia Perez", "Placa": "ABC019"},
    {"Cédula": 818345878, "Nombre": "Teresa Martinez Gonzalez", "Placa": "ABC020"},
    {"Cédula": 723456789, "Nombre": "Raul Lopez Sanchez", "Placa": "ABC021"},
    {"Cédula": 453467891, "Nombre": "Patricia Perez Martinez", "Placa": "ABC022"},
    {"Cédula": 345678092, "Nombre": "Miguel Gonzalez Rodriguez", "Placa": "ABC023"},
    {"Cédula": 456789022, "Nombre": "Eva Martinez Lopez", "Placa": "ABC024"},
    {"Cédula": 567892031, "Nombre": "Alejandro Sanchez Perez", "Placa": "ABC025"},
    {"Cédula": 698702134, "Nombre": "Natalia Rodriguez Martinez", "Placa": "ABC026"},
    {"Cédula": 788012345, "Nombre": "Gabriel Perez Sanchez", "Placa": "ABC027"},
    {"Cédula": 898123486, "Nombre": "Luisa Hernandez Gonzalez", "Placa": "ABC028"},
    {"Cédula": 212345678, "Nombre": "Andres Garcia Perez", "Placa": "ABC029"},
    {"Cédula": 113325878, "Nombre": "Cristina Martinez Gonzalez", "Placa": "ABC030"},
    {"Cédula": 324426789, "Nombre": "Javier Lopez Sanchez", "Placa": "ABC031"},
    {"Cédula": 434569780, "Nombre": "Marina Perez Martinez", "Placa": "ABC032"},
    {"Cédula": 354678903, "Nombre": "Pablo Gonzalez Rodriguez", "Placa": "ABC033"},
    {"Cédula": 455789112, "Nombre": "Clara Martinez Lopez", "Placa": "ABC034"},
    {"Cédula": 567790123, "Nombre": "Alberto Sanchez Perez", "Placa": "ABC035"},
    {"Cédula": 698901234, "Nombre": "Sara Rodriguez Martinez", "Placa": "ABC036"},
    {"Cédula": 780012355, "Nombre": "Lucas Perez Sanchez", "Placa": "ABC037"},
    {"Cédula": 811123456, "Nombre": "Lorena Hernandez Gonzalez", "Placa": "ABC038"},
    {"Cédula": 111234667, "Nombre": "Francisco Garcia Perez", "Placa": "ABC039"},
    {"Cédula": 212245518, "Nombre": "Luisa Martinez Gonzalez", "Placa": "ABC040"},
    {"Cédula": 323356789, "Nombre": "Eduardo Lopez Sanchez", "Placa": "ABC041"},
    {"Cédula": 434567899, "Nombre": "Ana Perez Martinez", "Placa": "ABC042"},
    {"Cédula": 345678001, "Nombre": "Jorge Gonzalez Rodriguez", "Placa": "ABC043"},
    {"Cédula": 457781112, "Nombre": "Maria Martinez Lopez", "Placa": "ABC044"},
    {"Cédula": 569870523, "Nombre": "David Sanchez Perez", "Placa": "ABC045"},
    {"Cédula": 679801243, "Nombre": "Carmen Rodriguez Martinez", "Placa": "ABC046"},
    {"Cédula": 780913335, "Nombre": "Javier Perez Sanchez", "Placa": "ABC047"},
    {"Cédula": 812123456, "Nombre": "Silvia Hernandez Gonzalez", "Placa": "ABC048"},
    {"Cédula": 221234167, "Nombre": "Ruben Garcia Perez", "Placa": "ABC049"},
    {"Cédula": 512345679, "Nombre": "Marta Martinez Gonzalez", "Placa": "ABC050"},
    {"Cédula": 423456790, "Nombre": "Joaquin Lopez Sanchez", "Placa": "ABC051"},
    {"Cédula": 334567890, "Nombre": "Carolina Perez Martinez", "Placa": "ABC052"},
    {"Cédula": 145678901, "Nombre": "Adrian Gonzalez Rodriguez", "Placa": "ABC053"},
    {"Cédula": 456789002, "Nombre": "Paula Martinez Lopez", "Placa": "ABC054"},
    {"Cédula": 568792103, "Nombre": "Alberto Sanchez Perez", "Placa": "ABC055"},
    {"Cédula": 679802144, "Nombre": "Beatriz Rodriguez Martinez", "Placa": "ABC056"},
    {"Cédula": 789012345, "Nombre": "Marcos Perez Sanchez", "Placa": "ABC057"},
    {"Cédula": 290123456, "Nombre": "Ana Hernandez Gonzalez", "Placa": "ABC058"},
    {"Cédula": 101824567, "Nombre": "Elena Garcia Perez", "Placa": "ABC059"},
    {"Cédula": 512335878, "Nombre": "Javier Martinez Gonzalez", "Placa": "ABC060"},
    {"Cédula": 423326889, "Nombre": "Maria Lopez Sanchez", "Placa": "ABC061"},
    {"Cédula": 334567890, "Nombre": "Gabriel Perez Martinez", "Placa": "ABC062"},
    {"Cédula": 645678901, "Nombre": "Sandra Gonzalez Rodriguez", "Placa": "ABC063"},
    {"Cédula": 256789012, "Nombre": "Luis Martinez Lopez", "Placa": "ABC064"},
    {"Cédula": 667890123, "Nombre": "Clara Sanchez Perez", "Placa": "ABC065"},
    {"Cédula": 578901234, "Nombre": "Mario Rodriguez Martinez", "Placa": "ABC066"},
    {"Cédula": 789012345, "Nombre": "Natalia Perez Sanchez", "Placa": "ABC067"},
    {"Cédula": 790123456, "Nombre": "Pablo Hernandez Gonzalez", "Placa": "ABC068"},
    {"Cédula": 301234567, "Nombre": "Cecilia Garcia Perez", "Placa": "ABC069"},
    {"Cédula": 412345678, "Nombre": "Diego Martinez Gonzalez", "Placa": "ABC070"},
    {"Cédula": 523456789, "Nombre": "Lorena Lopez Sanchez", "Placa": "ABC071"},
    {"Cédula": 334567890, "Nombre": "Fernando Perez Martinez", "Placa": "ABC072"},
    {"Cédula": 245678901, "Nombre": "Mariana Gonzalez Rodriguez", "Placa": "ABC073"},
    {"Cédula": 756789012, "Nombre": "Andres Martinez Lopez", "Placa": "ABC074"},
    {"Cédula": 767890123, "Nombre": "Camila Sanchez Perez", "Placa": "ABC075"},
    {"Cédula": 678901234, "Nombre": "Jorge Rodriguez Martinez", "Placa": "ABC076"},
    {"Cédula": 489012345, "Nombre": "Laura Perez Sanchez", "Placa": "ABC077"},
    {"Cédula": 190123456, "Nombre": "Santiago Hernandez Gonzalez", "Placa": "ABC078"},
    {"Cédula": 101234567, "Nombre": "Valeria Garcia Perez", "Placa": "ABC079"},
    {"Cédula": 114345658, "Nombre": "Roberto Martinez Gonzalez", "Placa": "ABC080"},
    {"Cédula": 122446588, "Nombre": "Daniela Lopez Sanchez", "Placa": "ABC081"},
    {"Cédula": 234567890, "Nombre": "Jose Perez Martinez", "Placa": "ABC082"},
    {"Cédula": 345678901, "Nombre": "Monica Gonzalez Rodriguez", "Placa": "ABC083"},
    {"Cédula": 456789012, "Nombre": "Ricardo Martinez Lopez", "Placa": "ABC084"},
    {"Cédula": 567890123, "Nombre": "Julia Sanchez Perez", "Placa": "ABC085"},
    {"Cédula": 678901234, "Nombre": "Eduardo Rodriguez Martinez", "Placa": "ABC086"},
    {"Cédula": 789012345, "Nombre": "Carolina Perez Sanchez", "Placa": "ABC087"},
    {"Cédula": 890123456, "Nombre": "Fernando Hernandez Gonzalez", "Placa": "ABC088"},
    {"Cédula": 201234570, "Nombre": "Lucia Garcia Perez", "Placa": "ABC089"},
    {"Cédula": 312345678, "Nombre": "Andres Martinez Gonzalez", "Placa": "ABC090"},
    {"Cédula": 123456788, "Nombre": "Gabriela Lopez Sanchez", "Placa": "ABC091"},
    {"Cédula": 134367890, "Nombre": "Roberto Perez Martinez", "Placa": "ABC092"},
    {"Cédula": 145678900, "Nombre": "Carla Gonzalez Rodriguez", "Placa": "ABC093"},
    {"Cédula": 256789001, "Nombre": "Javier Martinez Lopez", "Placa": "ABC094"},
    {"Cédula": 567890120, "Nombre": "Ana Sanchez Perez", "Placa": "ABC095"},
    {"Cédula": 678901231, "Nombre": "Diego Rodriguez Martinez", "Placa": "ABC096"},
    {"Cédula": 489012340, "Nombre": "Sofia Perez Sanchez", "Placa": "ABC097"},
    {"Cédula": 890123451, "Nombre": "Luis Hernandez Gonzalez", "Placa": "ABC098"},
    {"Cédula": 301234562, "Nombre": "Monica Garcia Perez", "Placa": "ABC099"},
    {"Cédula": 112345673, "Nombre": "Daniel Martinez Gonzalez", "Placa": "ABC100"}
]

#Espacios de parqueo
# La lista `espacios_parqueo` contiene diccionarios donde cada uno representa un espacio de parqueo
# en un parqueo vehicular, identificando el número de espacio, la placa del vehículo estacionado 
# (si lo hay), y la disponibilidad del espacio.

Espacios_Parqueo= [ 
    {"Espacios_Parqueo1_Ministerio_Trabajo": "MT", "MT1":"Disponible","MT2":"Disponible","MT3":"Disponible", "MT4":"Disponible", "MT5":"Disponible", "MT6":"Disponible","MT7":"Disponible", "Visitante MT1":"Disponible","Visitante MT2":"Disponible","Visitante MT3":"Disponible"},
    {"Espacios_Parqueo2_Contiguo_ULACIT": "CU",  "CU1":"Disponible","CU2":"Disponible","CU3":"Disponible", "CU4":"Disponible", "CU5":"Disponible", "CU6":"Disponible","CU7":"Disponible", "Visitante CU1":"Disponible","Visitante CU2":"Disponible","Visitante CU3":"Disponible"},
    {"Espacios_Parqueo3_Posterior_ULACIT":"PU","PU1":"Disponible","PU2":"Disponible","PU3":"Disponible", "PU4":"Disponible", "PU5":"Disponible", "PU6":"Disponible","PU7":"Disponible", "Visitante PU1":"Disponible","Visitante PU2":"Disponible","Visitante PU3":"Disponible"},
    {"Espacios_Parqueo4_Falcon_Yard":"FY", "FY1":"Disponible","FY2":"Disponible","FY3":"Disponible", "FY4":"Disponible", "FY5":"Disponible", "FY6":"Disponible","FY7":"Disponible", "Visitante FY1":"Disponible","Visitante FY2":"Disponible","Visitante FY3":"Disponible"},
    {"Espacios_Parqueo5_Interno_ULACIT":"IU", "IU1":"Disponible","IU2":"Disponible","IU3":"Disponible", "IU4":"Disponible", "IU5":"Disponible", "IU6":"Disponible","IU7":"Disponible", "Visitante IU1":"Disponible","Visitante IU2":"Disponible","Visitante IU3":"Disponible"},
    {"Espacios_Parqueo6_Museo_Ninos":"MN",  "MN1":"Disponible","MN2":"Disponible","MN3":"Disponible", "MN4":"Disponible", "MN5":"Disponible", "MN6":"Disponible","MN7":"Disponible", "Visitante MN1":"Disponible","Visitante MN2":"Disponible","Visitante MN3":"Disponible"}
]

# PERSONAL ADMINISTRATIVO
# Este tipo de estructura es útil para sistemas de administración de parqueos, donde es necesario
# relacionar a los usuarios con los vehículos que poseen, los espacios de parqueo que ocupan, 
# y los guardas responsables de la seguridad en el área.
guardas = [
    {"Cédula": 1234567, "nombre": "Juan Pérez González", "contraseña": "password1"},
    {"Cédula": 1234568, "nombre": "María Rodríguez López", "contraseña": "password2"},
    {"Cédula": 1234569, "nombre": "José Fernández Díaz", "contraseña": "password3"},
    {"Cédula": 1234570, "nombre": "Ana López Martínez", "contraseña": "password4"},
    {"Cédula": 1234571, "nombre": "Carlos Díaz Pérez", "contraseña": "password5"},
    {"Cédula": 1234572, "nombre": "Laura González Gutiérrez", "contraseña": "password6"},
    {"Cédula": 1234573, "nombre": "Luis Martínez Hernández", "contraseña": "password7"},
    {"Cédula": 1234574, "nombre": "Gabriela Pérez Sánchez", "contraseña": "password8"},
    {"Cédula": 1234575, "nombre": "Pedro Gutiérrez Romero", "contraseña": "password9"},
    {"Cédula": 1234576, "nombre": "Sofía Hernández Álvarez", "contraseña": "password10"},
    {"Cédula": 1234577, "nombre": "Diego Sánchez Torres", "contraseña": "password11"},
    {"Cédula": 1234578, "nombre": "Valeria Romero Ruiz", "contraseña": "password12"},
    {"Cédula": 1234579, "nombre": "Jorge Álvarez Ramírez", "contraseña": "password13"},
    {"Cédula": 1234580, "nombre": "Fernanda Torres Suárez", "contraseña": "password14"},
    {"Cédula": 1234581, "nombre": "Miguel Ruiz Flores", "contraseña": "password15"},
    {"Cédula": 1234582, "nombre": "Camila Ramírez Benítez", "contraseña": "password16"},
    {"Cédula": 1234583, "nombre": "Manuel Suárez Acuña", "contraseña": "password17"},
    {"Cédula": 1234584, "nombre": "Isabela Flores Castro", "contraseña": "password18"},
    {"Cédula": 1234585, "nombre": "Daniel Benítez Rojas", "contraseña": "password19"},
    {"Cédula": 1234586, "nombre": "Verónica Acuña Molina", "contraseña": "password20"},
    {"Cédula": 1234587, "nombre": "Alejandro Castro Vargas", "contraseña": "password21"},
    {"Cédula": 1234588, "nombre": "Paula Rojas Fernández", "contraseña": "password22"},
    {"Cédula": 1234589, "nombre": "Ricardo Molina Rojas", "contraseña": "password23"},
    {"Cédula": 1234590, "nombre": "Andrea Vargas Castro", "contraseña": "password24"},
]